# fly.toml app configuration file generated for contribution-analyzer on 2023-06-20T17:06:46-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "contribution-analyzer"
kill_signal = "SIGINT"
kill_timeout = 30
primary_region = "sjc"
processes = []

[experimental]
allowed_public_ports = []
auto_rollback = true

[mounts]
destination = "/data"
source = "data"

[deploy]
release_command = "node ./other/sentry-create-release.js"

[[services]]
internal_port = 8080
processes = ["app"]
protocol = "tcp"
script_checks = []

[services.concurrency]
hard_limit = 100
soft_limit = 80
type = "connections"

[[services.ports]]
force_https = true
handlers = ["http"]
port = 80

[[services.ports]]
handlers = ["tls", "http"]
port = 443
