# fly.toml app configuration file generated for contribution-analyzer on 2023-06-20T17:06:46-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "contribution-analyzer"
primary_region = "sjc"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
